# Generated by Django 2.1.7 on 2019-04-19 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportclub', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sportclubmodel',
            old_name='bankaccount_number',
            new_name='bankaccount_accountnumber',
        ),
        migrations.RenameField(
            model_name='sportclubmodel',
            old_name='bankaccount_name',
            new_name='bankaccount_ownername',
        ),
    ]
