# Generated by Django 2.1.7 on 2019-04-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportclub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportclubmodel',
            name='bankaccount_bankname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sportclubmodel',
            name='bankaccount_cardnumber',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sportclubmodel',
            name='bankaccount_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sportclubmodel',
            name='bankaccount_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sportclubmodel',
            name='bankaccount_shabanumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
