# Generated by Django 2.1.7 on 2019-05-11 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportclub', '0002_auto_20190419_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportclubmodel',
            name='terms_and_conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
