# Generated by Django 2.1.4 on 2019-04-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=264)),
                ('floor_type', models.CharField(blank=True, max_length=264)),
                ('locker', models.BooleanField()),
                ('drinking_water', models.BooleanField()),
                ('parking_area', models.BooleanField()),
                ('showers', models.IntegerField()),
                ('changing_room', models.IntegerField()),
                ('picture', models.ImageField(blank=True, upload_to='sportclub/salon/picture')),
            ],
        ),
    ]
