# Generated by Django 2.1.7 on 2019-04-10 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sportclub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=264)),
                ('floor_type', models.CharField(blank=True, max_length=264)),
                ('locker', models.BooleanField()),
                ('drinking_water', models.BooleanField()),
                ('parking_area', models.BooleanField()),
                ('shower', models.PositiveIntegerField()),
                ('changing_room', models.PositiveIntegerField()),
                ('sportclub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salons', to='sportclub.SportClubModel')),
            ],
        ),
        migrations.CreateModel(
            name='SalonPictureModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='sportclub/salon/picture')),
                ('Salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='salon.SalonModel')),
            ],
        ),
    ]
