# Generated by Django 2.1.4 on 2019-04-07 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sportclub', '0002_auto_20190407_2322'),
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonmodel',
            name='sportclub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salons', to='sportclub.SportClubModel'),
        ),
    ]
