# Generated by Django 2.1.7 on 2019-05-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonmodel',
            name='safe_keeping',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
