# Generated by Django 2.1.7 on 2019-05-21 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salon', '0002_salonmodel_safe_keeping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('start_time', models.DateTimeField()),
                ('duration', models.CharField(max_length=264)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('is_booked', models.BooleanField(default=False)),
                ('is_ready', models.BooleanField(default=False)),
                ('booker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='salon.SalonModel')),
            ],
        ),
    ]
