# Generated by Django 2.1.7 on 2019-05-22 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_salonmodel_safe_keeping'),
        ('session', '0002_remove_sessionmodel_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sessionmodel',
            unique_together={('salon', 'start_time')},
        ),
    ]
