# Generated by Django 2.1.7 on 2019-05-22 01:06

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_auto_20190522_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionmodel',
            name='start_time',
            field=django_jalali.db.models.jDateTimeField(),
        ),
    ]
