# Generated by Django 2.1.7 on 2019-05-22 01:14

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0005_auto_20190522_0536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionmodel',
            name='start_time',
        ),
        migrations.AddField(
            model_name='sessionmodel',
            name='day',
            field=django_jalali.db.models.jDateField(null=True),
        ),
        migrations.AddField(
            model_name='sessionmodel',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
