# Generated by Django 2.1.7 on 2019-05-31 11:00

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0007_lastdatamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastdatamodel',
            name='first_day',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lastdatamodel',
            name='last_day',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
