# Generated by Django 2.1.4 on 2019-03-23 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='CommonUser',
        ),
    ]
