# Generated by Django 2.1.7 on 2019-05-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='super_user_logs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
