# Generated by Django 2.1.7 on 2019-04-09 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonUserModel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='commonusers', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('slug', models.SlugField(unique=True)),
                ('first_name', models.CharField(max_length=216, null=True)),
                ('last_name', models.CharField(max_length=216, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('picture', models.ImageField(default='commonuser/default/coverpicture/default_profile_pic.jpg', upload_to='commonuser/coverpicture')),
            ],
        ),
    ]
