# Generated by Django 2.1.7 on 2019-04-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonusermodel',
            name='picture',
            field=models.ImageField(default='commonuser/default/default_commonuser.jpg', upload_to='commonuser/coverpicture'),
        ),
    ]
