# Generated by Django 2.1.4 on 2019-03-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonuser', '0002_auto_20190324_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonusermodel',
            name='first_name',
            field=models.CharField(max_length=216, null=True),
        ),
        migrations.AddField(
            model_name='commonusermodel',
            name='last_name',
            field=models.CharField(max_length=216, null=True),
        ),
        migrations.AlterField(
            model_name='commonusermodel',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
