# Generated by Django 2.1.7 on 2019-04-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masteruser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterusermodel',
            name='picture',
            field=models.ImageField(default='masteruser/default/default_masteruser.png', upload_to='masteruser/coverpicture'),
        ),
    ]
