# Generated by Django 2.1.7 on 2019-04-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masteruser', '0002_masterusermodel_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterusermodel',
            name='picture',
            field=models.ImageField(default='masteruser/default/default_masteruser.jpg', upload_to='masteruser/coverpicture'),
        ),
    ]
